version: "3"

services:
  mysql:
    build:
      context: .
    container_name: docker_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sukkiriSQL
      TZ: "Asia/Tokyo"
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"